{% set name = "mpg123" %}
{% set version = "1.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.bz2/download
  sha256: 00f7bf7ea64fcec2c9d07751d6ad8849343ee09c282ea3b0d5dd486e886e2ff3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f $PREFIX/lib/libmpg123${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libout123${SHLIB_EXT}  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [linux]

about:
  home: https://www.mpg123.de/
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: mpg123 - fast console MPEG Audio Player and decoder library

extra:
  recipe-maintainers:
    - hbredin
    - thomasfillon
