{% set name = "mpg123" %}
{% set version = "1.32.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.bz2/download
  sha256: ccdd1d0abc31d73d8b435fc658c79049d0a905b30669b6a42a03ad169dc609e6

build:
  number: 0
  run_exports:
      # Seems to have good compatibility
      # https://abi-laboratory.pro/index.php?view=timeline&l=mpg123
      # But the minor releases are not too often, so I think it is probably
      # best to play it safe
    - {{ pin_subpackage("mpg123", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - cmake  # [win]
    - ninja  # [win]
    - yasm  # [win]
    - pkg-config  # [unix]
  host:

test:
  commands:
    - test -f $PREFIX/lib/libmpg123${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libout123${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\mpg123.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\mpg123.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\out123.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\out123.lib exit 1  # [win]

about:
  home: https://www.mpg123.de/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: mpg123 - fast console MPEG Audio Player and decoder library

extra:
  recipe-maintainers:
    - hbredin
    - thomasfillon
    - bmcfee
