travis:
  secure:
    BINSTAR_TOKEN: tggv7+AKmQm6jw6Yb/wW+SlorOjHE2XWUX8h7McHf67ZMQmBenmNgKEd8K5DzYXPoDh9ivz7rwnoQKZLNhbSTui93D8T9RJMAd9HmFDGblmniY/r38dml6l2/JBp5L0HZpozkvhHYZodpE0v7xnjdJnwPXFtr08G1Iiuto4jSh/8+sfbO2h1vJi3VllbP+a3XCRCbyLUg4JpCHC8Nh3JWEmSoXz4BrJnrUEdcQmQvnVmOG064je7SSXUtcxDY51oKXtoCceGsEOALQRuVvy9oNRDDCQuI9rhAHq/x+ibe3pLtTL9WRI/go7YwG7CT34Csdp9nbH27rqz8N/aO/eehrvbYnk0kVoF57N6TU/07jc0AsqbW5XaNNLzutzUN73TBlU8uWQ3jcnFVLUhzsUkZ6+xerCn0XYYaM+L9zDLeKC8gI5wEM81wxmEuDRRlrpm1hnqs42Y+3bxtK1eMyTkewFxHfY9COg/eoXGy63KNzXVKRO7yzIkgeqHYjTRLUrDpnMLeq8AXNRMW+tNNAIC4pr5UJqDog5caVhy09ahcbAAooADJIDgKbnPijEWtGcoMKFkoeN+bTzN9OFFtTMs1b71sUku/W+bKZBxyvuNlvCUJQiKcSImcVc5OZfjfrs09VWDYRAG2NB/IwgOMZpDvsrvwN687K4CQKkAIeQl/CQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
